# docker-compose up (Run in attached mode)
# docker-compose up -d (Run in detached mode)
# docker-compose down (Shutdown and stop all the services and remove the container)
# docker-compose down -v (Shutdown and stop all the services and remove the container with volume removal)
# docker-compose up --build (Start the docker compose with rebuild the image)
# docker-compose build (Just build the image)

version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db:ro
    # container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: max
      # MONGO_INITDB_ROOT_PASSWORD: secret
      #- MONGO_INITDB_ROOT_USERNAME=max
      #- MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
    - ./env/mongo.env
    # networks:
    #  - goals-net
  backend:
    build: ./backend # Execute docker file
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-args: 1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  front-end:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: